### ISSUE TITLE
py3 or py2?

### ISSUE THREAD

**Issue by xhebox** [abbat/pclcmd#2]
```
Traceback (most recent call last):
  File "/bin/pclcmd", line 2257, in <module>
    pcl_ls_cmd(options, args)
  File "/bin/pclcmd", line 1837, in pcl_ls_cmd
    meta, dirs, files = pcl_list(options, pcl_remote_path(path))
  File "/bin/pclcmd", line 1000, in pcl_list
    part = pcl_query(options, method, url, args)
  File "/bin/pclcmd", line 875, in pcl_query
    return pcl_query_retry(options, method, url, args, headers, filename)
  File "/bin/pclcmd", line 802, in pcl_query_retry
    result = opener.open(request, timeout = options.timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/bin/pclcmd", line 344, in https_open
    return self.do_open(self._get_connection, req)
  File "/usr/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
TypeError: request() got an unexpected keyword argument 'encode_chunked'
```
I got this error on archlinux, but no error if python2 /bin/pclcmd, you should consider modifying the header to:
```
#!/usr/bin/env python2(or 3?)
```

**Comment by abbat** [comment]
Thanks!
